### ISSUE TITLE
Will v2.0.6 be available with "pip install tabcmd"

### ISSUE THREAD

**Issue by weeejw** [tableau/tabcmd#180]
Forgive my lack of knowledge but will 2.0.6 be available for pip install soon?   Currently pip install still installs v2.0.5.

**Comment by jacalata** [comment]
Yes it will - it should have automatically been available, it failed unexpectedly and I'm looking into it.

**Comment by jizreel** [comment]
Hello guys, I installed using "pip install tabcmd" from the last release (2.0.6), but after installation I verified that the installed version is still 2.0.5. I'm trying to refresh a data source but I'm getting the return below. Could it be due to the version?
In short, I need to publish a data source but the user has MFA authentication enabled. If you can help, please, thank you!

![image](https://user-images.githubusercontent.com/14808124/192538303-4c7ef82b-8c9c-4ba5-960e-69ed7066832c.png)

**Comment by jacalata** [comment]
I was hoping to get to this a lot faster, but I should have said: you can get 2.0.6 now by doing
> pip install tabcmd --pre

**Comment by jacalata** [comment]
2.0.7 is now available through pip. I'm sorry this took so long to get done!

**Comment by weeejw** [comment]
Appreciate it!Thanks,JosephOn Nov 10, 2022, at 16:54, Jac ***@***.***> wrote:﻿
2.0.7 is now available through pip. I'm sorry this took so long to get done!
