### ISSUE TITLE
tabcmd v2.0.12 not compiled to run on 64-bit machines

### ISSUE THREAD

**Issue by palk60** [tableau/tabcmd#263]
Tried running the v2.0.12 tabcmd.exe on a 64-bit Windows server and received an error saying that the app was not compatible with 64-bit machines.  Version 2.0.11 ran fine.

**Comment by jacalata** [comment]
I haven't figured out why - the github windows-latest OS that we build the executable on has been Server 2022 since 2022 https://github.blog/changelog/2022-01-11-github-actions-jobs-running-on-windows-latest-are-now-running-on-windows-server-2022/#

The build job appears to be using x64 libraries: https://github.com/tableau/tabcmd/actions/runs/5686928079/job/15414553014

**Comment by bcantoni** [comment]
This is fixed now with a new 2.0.13 release: https://github.com/tableau/tabcmd/releases/tag/v2.0.13
